using Semprg_Pisqorky.Model;

namespace Semprg_Pisqorky.Tiles;

/// <summary>
/// This tile is generated by the game.
/// It has no functionality, but the game shouldn't allow overriding this tile
/// </summary>
class TraditionalTile : Tile
{
    public sealed override Player? Occupant { get; set; }
    public sealed override Int2D Position { get; init; }

    public TraditionalTile(Player? occupant, Int2D position)
    {
        Occupant = occupant;
        Position = position;
    }
}